version: 2
jobs:
  microservice_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/pytest
  microservice_lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd microservices
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check
  cli_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd globalgiving
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/pytest
  cli_lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd globalgiving
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user 
            /home/circleci/.local/bin/black . --check
workflows:
  version: 2
  build-test:
    jobs:
      - microservice_test
      - microservice_lint
      - cli_test
      - cli_lint
